# Generated by Django 5.2.8 on 2025-11-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetask',
            name='role_in_task',
        ),
    ]
